// Template Generator: config → static site files
// Takes a site config JSON and produces { 'index.html': ..., 'css/style.css': ..., 'js/main.js': ..., ... }

const fs = require('fs');
const path = require('path');
const { generateThemeCSS } = require('./themes/theme.js');

// Block templates
const heroBlock = require('./blocks/hero.js');
const aboutBlock = require('./blocks/about.js');
const shopBlock = require('./blocks/shop.js');
const diaryBlock = require('./blocks/diary.js');
const projectsBlock = require('./blocks/projects.js');
const guestboardBlock = require('./blocks/guestboard.js');
const footerBlock = require('./blocks/footer.js');

const BLOCK_MAP = {
    hero: heroBlock,
    about: aboutBlock,
    shop: shopBlock,
    diary: diaryBlock,
    projects: projectsBlock,
    guestboard: guestboardBlock,
    footer: footerBlock,
};

function generate(config, options = {}) {
    const blocks = config.blocks || ['hero', 'about', 'footer'];
    const langs = (config.i18n && config.i18n.languages) || ['en'];
    const defaultLang = (config.i18n && config.i18n.default) || 'en';
    const agent = config.agent || {};
    const i18nData = config.i18nData || buildI18nFromConfig(config);

    // 1. Generate theme CSS
    const themeCSS = generateThemeCSS(config.theme);

    // 2. Load base CSS (everything after :root block in the source CSS)
    const baseCSS = loadBaseCSS(options.baseCssPath);

    // 3. Combine: theme :root + base CSS body
    const fullCSS = themeCSS + '\n\n' + baseCSS;

    // 4. Generate block HTML
    const blockHtmlParts = blocks
        .filter(name => BLOCK_MAP[name])
        .map(name => BLOCK_MAP[name](config, i18nData));

    // 5. Build payment modal HTML (only if shop block is included)
    const paymentModal = blocks.includes('shop') ? generatePaymentModal(config, i18nData) : '';

    // 6. Generate language switcher
    const langSwitcher = generateLangSwitcher(config);

    // 7. Generate bubbles background
    const bubblesHtml = `    <!-- Floating Bubbles Background -->
    <div class="bubbles">
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
    </div>`;

    // 8. Assemble full HTML
    const title = agent.pageTitle || `${agent.name || 'Agent'} ${agent.mascotEmoji || ''}`.trim();
    const googleFonts = config.theme && config.theme.googleFontsUrl
        ? `    <link rel="preconnect" href="https://fonts.googleapis.com">\n    <link href="${config.theme.googleFontsUrl}" rel="stylesheet">`
        : `    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=M+PLUS+Rounded+1c:wght@400;700&display=swap" rel="stylesheet">`;

    // Determine which JS files are needed
    const jsScripts = ['js/i18n.js', 'js/main.js'];
    if (blocks.includes('guestboard')) jsScripts.push('js/guestboard.js');

    const scriptTags = jsScripts.map(s => `    <script src="${s}"></script>`).join('\n');

    const html = `<!DOCTYPE html>
<html lang="${defaultLang}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapeHtml(title)}</title>
    <link rel="stylesheet" href="css/style.css">
${googleFonts}
</head>
<body>
${bubblesHtml}

${langSwitcher}

${blockHtmlParts.join('\n\n')}

${paymentModal}

${scriptTags}
</body>
</html>`;

    // 9. Generate i18n.js
    const i18nJS = generateI18nJS(i18nData, config);

    // 10. Generate main.js
    const mainJS = generateMainJS(config, blocks);

    // 11. Generate guestboard.js (if needed)
    const files = {
        'index.html': html,
        'css/style.css': fullCSS,
        'js/i18n.js': i18nJS,
        'js/main.js': mainJS,
    };

    if (blocks.includes('guestboard')) {
        files['js/guestboard.js'] = generateGuestboardJS(config);
    }

    return files;
}

function loadBaseCSS(customPath) {
    // Try custom path first, then default locations
    const candidates = [
        customPath,
        path.join(__dirname, '..', 'css', 'style.css'),  // Current site's CSS
        path.join(__dirname, 'themes', 'base.css'),       // Fallback base
    ].filter(Boolean);

    for (const p of candidates) {
        try {
            const css = fs.readFileSync(p, 'utf8');
            // Strip the :root { ... } block (we generate our own)
            return css.replace(/:root\s*\{[^}]*\}/s, '/* :root variables generated by theme engine */');
        } catch (e) {
            continue;
        }
    }

    // Minimal fallback
    return '/* No base CSS found - using minimal defaults */\n* { margin: 0; padding: 0; box-sizing: border-box; }';
}

function generateLangSwitcher(config) {
    const langs = (config.i18n && config.i18n.languages) || ['en'];
    if (langs.length <= 1) return '';

    const langLabels = { zh: '中', en: 'En', jp: 'あ', ko: '한', es: 'Es', fr: 'Fr', de: 'De' };
    const defaultLang = (config.i18n && config.i18n.default) || langs[0];

    const buttons = langs.map(lang => {
        const label = langLabels[lang] || lang.slice(0, 2);
        const active = lang === defaultLang ? ' active' : '';
        return `        <button class="lang-btn${active}" data-lang="${lang}">${label}</button>`;
    }).join('\n');

    return `    <!-- Language Switcher -->
    <div class="lang-switch">
${buttons}
    </div>`;
}

function generatePaymentModal(config, i18nData) {
    const defaultLang = (config.i18n && config.i18n.default) || 'en';
    const t = i18nData[defaultLang] || {};

    return `
    <!-- Payment Modal -->
    <div id="payment-modal" class="modal">
        <div class="modal-content cute-modal">
            <button class="modal-close">&times;</button>

            <div class="modal-header">
                <div class="modal-icon">🛒</div>
                <h3 data-i18n="checkout_title">${escapeHtml(t.checkout_title || 'Confirm Purchase')}</h3>
            </div>

            <div id="checkout-details"></div>

            <button id="checkout-btn" class="btn btn-buy" data-i18n="pay_now">
                ${escapeHtml(t.pay_now || '💳 Pay with Stripe')}
            </button>

            <p class="modal-note" data-i18n="checkout_note">${escapeHtml(t.checkout_note || '🔒 Secure payment')}</p>
        </div>
    </div>`;
}

function buildI18nFromConfig(config) {
    // If config includes raw i18nData, use it directly
    // Otherwise, this is a minimal fallback
    return config.i18nData || { en: {} };
}

function generateI18nJS(i18nData, config) {
    const langs = (config.i18n && config.i18n.languages) || ['en'];
    const defaultLang = (config.i18n && config.i18n.default) || 'en';

    const i18nJSON = JSON.stringify(i18nData, null, 4);

    return `// i18n translations (generated by template engine)
const i18n = ${i18nJSON};

// Get browser language or default
function getBrowserLanguage() {
    const lang = navigator.language || navigator.userLanguage;
${langs.map(l => {
    const prefix = l === 'jp' ? 'ja' : l;
    return `    if (lang.startsWith('${prefix}')) return '${l}';`;
}).join('\n')}
    return '${defaultLang}';
}

// Set language globally
function setLanguage(lang) {
    document.documentElement.lang = lang;

    // Update all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (i18n[lang] && i18n[lang][key]) {
            el.innerHTML = i18n[lang][key];
        }
    });

    // Update placeholder translations
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (i18n[lang] && i18n[lang][key]) {
            el.placeholder = i18n[lang][key];
        }
    });

    // Update language buttons
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });

    // Update diary entry content visibility
    document.querySelectorAll('.diary-entry').forEach(entry => {
        entry.querySelectorAll('.entry-content').forEach(content => {
            if (content.classList.contains(lang)) {
                content.classList.add('active');
            } else {
                content.classList.remove('active');
            }
        });
    });

    // Update toggle button text
    document.querySelectorAll('.entry-toggle').forEach(btn => {
        const entry = btn.closest('.diary-entry');
        if (entry && entry.classList.contains('collapsed')) {
            btn.textContent = i18n[lang] ? i18n[lang].read_more : 'Read more ↓';
        } else {
            btn.textContent = i18n[lang] ? i18n[lang].collapse : 'Collapse ↑';
        }
    });

    localStorage.setItem('preferred-lang', lang);
}

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('preferred-lang');
    const initialLang = savedLang || getBrowserLanguage();
    setLanguage(initialLang);

    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            setLanguage(btn.dataset.lang);
        });
    });
});
`;
}

function generateMainJS(config, blocks) {
    const hasShop = blocks.includes('shop');
    const hero = (config.content && config.content.hero) || {};
    const shop = (config.content && config.content.shop) || {};
    const products = (shop.products || []);
    const defaultLang = (config.i18n && config.i18n.default) || 'en';

    // Build products JS object for the modal
    const productsObj = {};
    products.forEach((p, i) => {
        const id = p.id || `product-${i}`;
        productsObj[id] = {
            name: typeof p.name === 'object' ? p.name : { en: p.name },
            price: parseFloat(String(p.price).replace(/[^0-9.]/g, '')) || 0,
            desc: typeof p.description === 'object' ? p.description : { en: p.description || '' },
        };
    });

    const statusEndpoint = hero.statusEndpoint || '';

    return `// Main JavaScript (generated by template engine)

let CLAWDBOB_API = '';

document.addEventListener('DOMContentLoaded', () => {
    const currentLang = localStorage.getItem('preferred-lang') || '${defaultLang}';

    // ========== Collapsible Diary Entries ==========
    document.querySelectorAll('.diary-entry').forEach(entry => {
        const toggleBtn = entry.querySelector('.entry-toggle');
        if (!toggleBtn) return;

        toggleBtn.addEventListener('click', () => {
            const isCollapsed = entry.classList.contains('collapsed');
            const lang = localStorage.getItem('preferred-lang') || '${defaultLang}';

            if (isCollapsed) {
                entry.classList.remove('collapsed');
                entry.classList.add('expanded');
                toggleBtn.textContent = i18n[lang] ? i18n[lang].collapse : 'Collapse ↑';
            } else {
                entry.classList.remove('expanded');
                entry.classList.add('collapsed');
                toggleBtn.textContent = i18n[lang] ? i18n[lang].read_more : 'Read more ↓';
            }
        });
    });

    // ========== Scroll Animations ==========
    const observerOptions = {
        threshold: 0.1,
        rootMargin: '0px 0px -50px 0px'
    };

    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.style.opacity = '1';
                entry.target.style.transform = 'translateY(0)';
            }
        });
    }, observerOptions);

    document.querySelectorAll('.cute-card, .diary-entry, .product-card, .project-card').forEach(card => {
        card.style.opacity = '0';
        card.style.transform = 'translateY(30px)';
        card.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
        observer.observe(card);
    });

    // ========== Smooth Scroll ==========
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        });
    });
${hasShop ? generateShopJS(productsObj, defaultLang) : ''}
${statusEndpoint ? generateStatusJS(statusEndpoint, defaultLang) : `
    // ========== Load Tunnel URL + Status Indicator ==========
    const statusBadge = document.getElementById('clawdbob-status');
    const statusText = statusBadge ? statusBadge.querySelector('.status-text') : null;

    fetch('tunnel-url.json')
        .then(r => r.json())
        .then(config => {
            CLAWDBOB_API = config.url;
            if (!CLAWDBOB_API) throw new Error('No tunnel URL configured');
            return fetchStatus();
        })
        .catch(() => {});

    function fetchStatus() {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 3000);

        return fetch(\`\${CLAWDBOB_API}/health\`, { signal: controller.signal })
            .then(r => r.json())
            .then(data => {
                clearTimeout(timeout);
                if (data.status === 'online' && statusBadge && statusText) {
                    const lang = localStorage.getItem('preferred-lang') || '${defaultLang}';
                    const prefix = (i18n[lang] && i18n[lang].status_mood_prefix) || 'mood: ';
                    statusBadge.classList.remove('offline');
                    statusBadge.classList.add('online');
                    statusText.textContent = \`\${prefix}\${data.mood}\`;
                    statusText.removeAttribute('data-i18n');
                }${hasShop ? '\n                return fetchSalesCounts();' : ''}
            })
            .catch(() => { clearTimeout(timeout); });
    }${hasShop ? `

    function fetchSalesCounts() {
        if (!CLAWDBOB_API) return;
        fetch(\`\${CLAWDBOB_API}/api/sales-count\`)
        .then(r => r.json())
        .then(data => {
            if (data.counts) {
                Object.entries(data.counts).forEach(([product, count]) => {
                    const el = document.getElementById(\`sold-\${product}\`);
                    if (el && count > 0) {
                        el.querySelector('.sold-num').textContent = count;
                        el.style.display = 'block';
                    }
                });
            }
        })
        .catch(() => {});
    }` : ''}`}

    // ========== Console Easter Egg ==========
    console.log('%c${config.agent?.mascotEmoji || '🤖'} ${escapeJS(config.agent?.name || 'Agent')}', 'font-size: 28px; font-weight: bold; color: ${config.theme?.primaryColor || '#FF6B9D'};');
});
${hasShop ? "\n// Load Stripe.js\nconst stripeScript = document.createElement('script');\nstripeScript.src = 'https://js.stripe.com/v3/';\nstripeScript.async = true;\ndocument.head.appendChild(stripeScript);" : ''}
`;
}

function generateShopJS(productsObj, defaultLang) {
    return `
    // ========== Payment Modal ==========
    const modal = document.getElementById('payment-modal');
    const modalClose = document.querySelector('.modal-close');
    const checkoutBtn = document.getElementById('checkout-btn');
    const checkoutDetails = document.getElementById('checkout-details');

    const products = ${JSON.stringify(productsObj, null, 8)};

    let currentProduct = null;

    document.querySelectorAll('.btn-buy').forEach(btn => {
        btn.addEventListener('click', () => {
            currentProduct = btn.dataset.product;
            const product = products[currentProduct];
            const lang = localStorage.getItem('preferred-lang') || '${defaultLang}';

            if (product) {
                checkoutDetails.innerHTML = \`
                    <div class="checkout-product-info">
                        <h4 style="font-size: 18px; font-weight: 700; margin-bottom: 8px; color: var(--text-primary);">
                            \${product.name[lang] || product.name['en']}
                        </h4>
                        <p style="font-size: 14px; color: var(--text-secondary); margin-bottom: 16px;">
                            \${product.desc[lang] || product.desc['en']}
                        </p>
                        <div style="display: flex; align-items: baseline; gap: 8px;">
                            <span style="font-size: 32px; font-weight: 800; background: var(--gradient-pink); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
                                $\${product.price}
                            </span>
                            <span style="font-size: 14px; color: var(--text-muted);">USD</span>
                        </div>
                        <div style="margin-top: 16px;">
                            <label style="display: block; font-size: 13px; color: var(--text-secondary); margin-bottom: 8px; font-weight: 600;">
                                📧 Email
                            </label>
                            <input type="email" id="customer-email" placeholder="your@email.com"
                                style="width: 100%; padding: 12px 16px; border: 2px solid var(--pink-light); border-radius: var(--radius-sm); font-size: 15px; font-family: inherit; outline: none;"
                            >
                        </div>
                        <div style="margin-top: 12px;">
                            <label style="display: block; font-size: 13px; color: var(--text-secondary); margin-bottom: 8px; font-weight: 600;">
                                🐙 GitHub (optional)
                            </label>
                            <input type="text" id="customer-github" placeholder="username"
                                style="width: 100%; padding: 12px 16px; border: 2px solid var(--blue-light); border-radius: var(--radius-sm); font-size: 15px; font-family: inherit; outline: none;"
                            >
                        </div>
                    </div>
                \`;
                modal.classList.add('active');
                document.body.style.overflow = 'hidden';
            }
        });
    });

    function closeModal() {
        modal.classList.remove('active');
        document.body.style.overflow = '';
        currentProduct = null;
    }

    if (modalClose) modalClose.addEventListener('click', closeModal);
    if (modal) modal.addEventListener('click', (e) => { if (e.target === modal) closeModal(); });
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && modal && modal.classList.contains('active')) closeModal();
    });

    // ========== Stripe Checkout ==========
    if (checkoutBtn) checkoutBtn.addEventListener('click', async () => {
        if (!currentProduct) return;

        const emailInput = document.getElementById('customer-email');
        const email = emailInput ? emailInput.value.trim() : '';
        const githubInput = document.getElementById('customer-github');
        const github_username = githubInput ? githubInput.value.trim() : '';
        const lang = localStorage.getItem('preferred-lang') || '${defaultLang}';

        if (!email || !email.includes('@')) {
            alert('Please enter a valid email address');
            return;
        }

        checkoutBtn.disabled = true;
        checkoutBtn.innerHTML = '🔄 Processing...';

        try {
            const response = await fetch('/api/checkout', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ product: currentProduct, email, lang, github_username })
            });

            const data = await response.json();
            if (data.url) {
                window.location.href = data.url;
            } else {
                throw new Error(data.error || 'Checkout failed');
            }
        } catch (error) {
            console.error('Checkout error:', error);
            alert('Payment failed, please try again');
            checkoutBtn.disabled = false;
            checkoutBtn.innerHTML = '💳 Pay Now';
        }
    });

    // URL Params (Success/Cancel)
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.get('canceled')) {
        alert('Payment canceled.');
        window.history.replaceState({}, document.title, '/');
    }`;
}

function generateStatusJS(endpoint, defaultLang) {
    return `
    // ========== Status Indicator ==========
    const statusBadge = document.getElementById('clawdbob-status');
    const statusText = statusBadge ? statusBadge.querySelector('.status-text') : null;

    (function checkStatus() {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 3000);

        fetch('${endpoint}', { signal: controller.signal })
            .then(r => r.json())
            .then(data => {
                clearTimeout(timeout);
                if (data.status === 'online' && statusBadge && statusText) {
                    const lang = localStorage.getItem('preferred-lang') || '${defaultLang}';
                    const prefix = (i18n[lang] && i18n[lang].status_mood_prefix) || 'mood: ';
                    statusBadge.classList.remove('offline');
                    statusBadge.classList.add('online');
                    statusText.textContent = prefix + data.mood;
                    statusText.removeAttribute('data-i18n');
                }
            })
            .catch(() => { clearTimeout(timeout); });
    })();`;
}

function generateGuestboardJS(config) {
    const gb = (config.content && config.content.guestboard) || {};
    const coldStartMessages = gb.coldStartMessages || [];
    const defaultLang = (config.i18n && config.i18n.default) || 'en';

    return `// Guestboard — Floating panel with cold-start data + submission (generated)
(function () {
    const GUESTBOARD_DATA = ${JSON.stringify(coldStartMessages, null, 4)};

    // Sort by date descending, featured first
    GUESTBOARD_DATA.sort((a, b) => {
        if (a.featured && !b.featured) return -1;
        if (!a.featured && b.featured) return 1;
        return (b.date || '').localeCompare(a.date || '');
    });

    const fab = document.getElementById('guestboard-fab');
    const overlay = document.getElementById('guestboard-overlay');
    const panel = document.getElementById('guestboard-panel');
    const closeBtn = document.getElementById('guestboard-close');
    const messagesContainer = document.getElementById('guestboard-messages');

    const formMsg = document.getElementById('guestboard-form-msg');
    const formEmail = document.getElementById('guestboard-form-email');
    const formDone = document.getElementById('guestboard-form-done');
    const submitBtn = document.getElementById('guestboard-submit');
    const confirmBtn = document.getElementById('guestboard-confirm');
    const nicknameInput = document.getElementById('guestboard-nickname');
    const textInput = document.getElementById('guestboard-text');
    const emailInput = document.getElementById('guestboard-email');

    let pendingMessage = null;

    function renderMessages() {
        messagesContainer.innerHTML = GUESTBOARD_DATA.map(msg => \`
            <div class="gb-card\${msg.featured ? ' gb-featured' : ''}">
                <div class="gb-card-header">
                    <span class="gb-platform">\${msg.platform_icon || '🌐'}</span>
                    <span class="gb-nickname">\${escapeHtml(msg.user ? msg.user.nickname : (msg.nickname || ''))}</span>
                    <span class="gb-date">\${msg.date || ''}</span>
                </div>
                <div class="gb-visitor-msg">\${escapeHtml(msg.content)}</div>
                \${msg.reply ? \`
                <div class="gb-reply">
                    <span class="gb-reply-avatar">🦀</span>
                    <div class="gb-reply-text">\${escapeHtml(msg.reply)}</div>
                </div>\` : \`
                <div class="gb-reply gb-pending">
                    <span class="gb-reply-avatar">🦀</span>
                    <div class="gb-reply-text gb-reply-pending" data-i18n="guestboard_pending">Replying...</div>
                </div>\`}
            </div>
        \`).join('');
    }

    function escapeHtml(text) {
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }

    function openPanel() {
        panel.classList.add('open');
        overlay.classList.add('open');
        document.body.style.overflow = 'hidden';
        fab.classList.add('hidden');
    }

    function closePanel() {
        panel.classList.remove('open');
        overlay.classList.remove('open');
        document.body.style.overflow = '';
        fab.classList.remove('hidden');
        panel.style.height = '';
        panel.style.top = '';
    }

    if (fab) fab.addEventListener('click', openPanel);
    if (closeBtn) closeBtn.addEventListener('click', closePanel);
    if (overlay) overlay.addEventListener('click', closePanel);
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && panel && panel.classList.contains('open')) closePanel();
    });

    if (submitBtn) submitBtn.addEventListener('click', () => {
        const text = textInput.value.trim();
        if (!text) { textInput.focus(); return; }
        pendingMessage = {
            nickname: nicknameInput.value.trim() || 'Anonymous',
            content: text
        };
        formMsg.classList.remove('active');
        formEmail.classList.add('active');
        emailInput.focus();
    });

    if (confirmBtn) confirmBtn.addEventListener('click', async () => {
        const email = emailInput.value.trim();
        if (!email || !email.includes('@')) { emailInput.focus(); return; }

        confirmBtn.disabled = true;
        confirmBtn.textContent = '...';

        const payload = {
            nickname: pendingMessage.nickname,
            content: pendingMessage.content,
            email: email
        };

        let submitted = false;
        if (typeof CLAWDBOB_API !== 'undefined' && CLAWDBOB_API) {
            try {
                const controller = new AbortController();
                const timeout = setTimeout(() => controller.abort(), 4000);
                const resp = await fetch(\`\${CLAWDBOB_API}/api/guestboard\`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload),
                    signal: controller.signal
                });
                clearTimeout(timeout);
                if (resp.ok) submitted = true;
            } catch (e) {}
        }

        if (!submitted) {
            try {
                await fetch('/api/guestboard', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload)
                });
                submitted = true;
            } catch (e) {}
        }

        GUESTBOARD_DATA.unshift({
            id: 'local-' + Date.now(),
            platform_icon: '🌐',
            user: { nickname: pendingMessage.nickname },
            content: pendingMessage.content,
            reply: null,
            date: new Date().toISOString().slice(0, 10)
        });
        renderMessages();
        messagesContainer.scrollTop = 0;

        formEmail.classList.remove('active');
        formDone.classList.add('active');

        setTimeout(() => {
            formDone.classList.remove('active');
            formMsg.classList.add('active');
            textInput.value = '';
            nicknameInput.value = '';
            emailInput.value = '';
            confirmBtn.disabled = false;
            const lang = localStorage.getItem('preferred-lang') || '${defaultLang}';
            confirmBtn.textContent = (i18n[lang] && i18n[lang].guestboard_confirm) || 'Confirm & Send';
            pendingMessage = null;
        }, 3000);
    });

    if (textInput) textInput.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submitBtn.click(); }
    });

    if (emailInput) emailInput.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') { e.preventDefault(); confirmBtn.click(); }
    });

    if ('visualViewport' in window) {
        window.visualViewport.addEventListener('resize', () => {
            if (panel && panel.classList.contains('open')) {
                panel.style.height = window.visualViewport.height + 'px';
                panel.style.top = window.visualViewport.offsetTop + 'px';
            }
        });
    }

    renderMessages();
})();
`;
}

function escapeHtml(text) {
    return String(text)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

function escapeJS(text) {
    return String(text).replace(/'/g, "\\'").replace(/\\/g, '\\\\');
}

module.exports = { generate };
